import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { API_URL, AUTH_URL, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI } from '../constants/spotify-auth';


/*
  Generated by ChatGPT, an OpenAI language model
*/

@Injectable({
  providedIn: 'root'
})
export class SpotifyAuthService {

  private readonly scopes = [
    'user-read-private',
    'user-read-email',
    'playlist-modify-public',
    'playlist-modify-private'
  ];

  constructor(private http: HttpClient) {}

  authorize(): void {
    const url = AUTH_URL +
      `?client_id=${CLIENT_ID}` +
      `&response_type=code` +
      `&redirect_uri=${encodeURIComponent(REDIRECT_URI)}` +
      `&scope=${encodeURIComponent(this.scopes.join(' '))}`;

    window.location.href = url;
  }

  getToken(code: string): Observable<any> {
    const body = `grant_type=authorization_code` +
      `&code=${code}` +
      `&redirect_uri=${encodeURIComponent(REDIRECT_URI)}` +
      `&client_id=${CLIENT_ID}` +
      `&client_secret=${CLIENT_SECRET}`;

    const headers = new HttpHeaders({
      'Content-Type': 'application/x-www-form-urlencoded'
    });

    return this.http.post<any>(API_URL, body, { headers });
  }

}
